apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sms-relay.fullname" . }}-data
  labels:
    {{- include "sms-relay.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- with .Values.persistence.data.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
